version: "3.6"
services:
  timescale:
    image: timescale/timescaledb:2.4.2-pg12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: fedormelexin/graphql-engine-arm64
    ports:
      - "8080:8080"
    depends_on:
      - "timescale"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@timescale:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: mylongsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    command:
      - graphql-engine
      - serve
      - --enable-console
volumes:
  db_data:
